# ğŸ› ï¸ Dependabot configuration file for keeping dependencies up-to-date ğŸš€
version: 2
updates:
  # ğŸ“¦ NPM Dependencies
  - package-ecosystem: "npm" 
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"

  # ğŸ³ Devcontainer Dependencies
  - package-ecosystem: "devcontainers" 
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"

  # ğŸ” GitHub Actions Dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"